name: flutter_form_builder
description: This package helps in creation of forms in Flutter by removing the boilerplate code, reusing validation, react to changes, and collect final user input.
version: 6.0.1
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  community_material_icon: ^5.4.55
  country_pickers: ^2.0.0
  date_range_picker: ^1.0.6
  datetime_picker_formfield: ^2.0.0
  dropdown_search: ^0.6.3
  file_picker: ^3.0.3
  flutter_colorpicker: ^0.5.0
  flutter_chips_input: ^1.9.5
  flutter_datetime_picker: ^1.4.0
  flutter_touch_spin: ^2.0.0-nullsafety.1
  flutter_typeahead: "<=1.9.1"
  image_picker: ^0.8.2
  image_picker_for_web: ^2.1.1
  intl: ^0.17.0
  permission_handler: ^8.1.3
  phone_number: ^0.11.0+1
  rating_bar: ^0.2.0
  signature: ^4.1.1
  validators: ^3.0.0

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
